targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
            - lib/models/*
      freezed:
        generate_for:
          include:
            - lib/models/*
