[[plugins]]

  package = "netlify-plugin-flutter"

   [plugins.inputs]
    channel = "stable"

[build]
   command = "flutter pub run build_runner build && flutter build web --release"
   publish = "build/web"